name: OpenFire Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest # For GPU tests, self-hosted runners with GPUs would be needed
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    # Note: CUDA and GStreamer are not installed in this basic CI setup.
    # Tests requiring these would need a more complex environment or be skipped.
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install PyTorch for CPU first to avoid large CUDA downloads on basic CI runners
        # If GPU testing is set up, this logic would change
        pip install torch==2.0.1 --index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
        pip install -e . # Install OpenFire in editable mode
        pip install pytest ruff # Install dev dependencies for CI steps

    - name: Lint with Ruff
      run: |
        ruff check .

    - name: Test with Pytest
      run: |
        pytest # Add markers to skip GPU/GStreamer tests if needed (e.g., pytest -m "not gpu") 